version: '3.8'
services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_container:/data/db
    # container_name: khub-mongo

  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo-express
      ME_CONFIG_MONGODB_ADMINPASSWORD: mysecretpassword
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mysecretpassword@mongo:27017/
    ports:
      - 8081:8081
    depends_on:
      - mongo
    # container_name: khub-mongo-express

  rml-mapper:
    image: rmlio/rmlmapper-java:latest
    restart: always
    profiles: ["cli-only"]

volumes:
  mongodb_container: