version: '3.8'
services:
  fuseki:
    image: fuseki
    entrypoint: "" # Overrides the default entrypoint
    environment: 
      - JAVA_OPTIONS=-Xmx4096m -Xms2048m
    command: sh -c "$$JAVA_HOME/bin/java $$JAVA_OPTIONS -jar $$FUSEKI_JAR --config $$FUSEKI_DIR/configuration/explorer-config.ttl --ping"

    build:
      args: 
        - JENA_VERSION=4.7.0
      # Locally uses the downloaded Dockerfile with scripts from 
      # https://repo1.maven.org/maven2/org/apache/jena/jena-fuseki-server/4.7.0/
      context: ./fuseki/
      dockerfile: Dockerfile
    ports:
      - 3030:3030
    volumes:
      - ../configuration:/fuseki/configuration
      - ../databases:/fuseki/databases

  explorer:
    image: khub-explorer
    depends_on:
      - fuseki
    build:
      args:
        - FUSEKI_ENDPOINT=http://localhost:3030/
        - FUSEKI_SERVICE=dataset
        - CONFLUENCE_ENDPOINT=
        # Please put your corporate email address:
        - CONFLUENCE_EMAIL=
        # Please create and put your private Confluence API token here:
        # See (https://id.atlassian.com/manage-profile/security/api-tokens)
        - CONFLUENCE_TOKEN=
        - LOGGING_ENDPOINT=
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000