name: Knowledge Hub Pipeline
on: push

env:
  JDK_VERSION: 17
  NODE_VERSION: 18
  FUSEKI_VERSION: 4.7.0

jobs:
  khub_builder:
    name: Knowledge Hub Builder
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK ${{env.JDK_VERSION}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{env.JDK_VERSION}}
          distribution: temurin

      - name: Build KHub Builder
        run: |
          cd ./khub-builder
          mvn --batch-mode --update-snapshots package

      - name: Publish KHub Builder
        uses: actions/upload-artifact@v3
        with:
          name: khub-builder
          path: |
            ./khub-builder/target/*.jar

      - name: Copy Resources
        run: |
          rm -i ./configuration/*
          cp ./khub-builder/src/main/resources/config.properties ./configuration/config.properties
          cp ./khub-builder/src/main/resources/docker-compose.yml ./resources/docker-compose.yml

      - name: Publish Resources
        uses: actions/upload-artifact@v3
        with:
          name: khub-builder
          path: |
            ./configuration/
            ./resources/

  khub_explorer:
    name: Knowledge Hub Explorer
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Build KHub Explorer
        run: |
          cd ./khub-explorer
          npm ci
          npm run build

      - name: Copy KHub Explorer Artifacts
        run: |
          cp -r ./khub-explorer/build ./explorer
          cp ./khub-explorer/Dockerfile ./explorer/Dockerfile

      - name: Download Fuseki Docker ${{env.FUSEKI_VERSION}}
        run: |
          cd ./explorer
          mkdir fuseki
          wget https://repo1.maven.org/maven2/org/apache/jena/jena-fuseki-docker/${{env.FUSEKI_VERSION}}/jena-fuseki-docker-${{env.FUSEKI_VERSION}}.zip
          unzip -j ./jena-fuseki-docker-${{env.FUSEKI_VERSION}}.zip -d ./fuseki          

      - name: Publish KHub Explorer
        uses: actions/upload-artifact@v3
        with:
          name: khub-explorer
          path: |
            ./configuration/
            ./explorer/
            ./khub-explorer-compose.yaml