name: Knowledge Hub Builder CI

on: [push]

jobs:
  khub-builder:
    name: KHub Builder
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build KHub Builder
        run: |
          cd ./khub-builder
          mvn --batch-mode --update-snapshots package

      - name: Publish Artifact
        uses: actions/upload-artifact@v3
        with:
          name: khub-builder
          path: |
            ./khub-builder/target/*.jar

      - name: Copy Resources
        run: |
          cp "./khub-builder/src/main/resources/config.properties" "./configuration/config.properties"
          cp "./khub-builder/src/main/resources/docker-compose.yml" "./resources/docker-compose.yml"

      - name: Publish Resources
        uses: actions/upload-artifact@v3
        with:
          name: khub-builder
          path: |
            ./configuration/
            ./resources/
